- src/commands/slack-jahia.yml
Hope this will be the final fix for this issue
Here's what I have locally:
```
~$ export DOCKER_COMMAND="```docker pull jahia/<< parameters.docker_repo >>:<< parameters.docker_image_tag >>```"
-bash: warning: here-document at line 1 delimited by end-of-file (wanted `parameters.docker_repo')
-bash: warning: here-document at line 1 delimited by end-of-file (wanted `parameters.docker_image_tag')
-bash: command substitution: line 1: syntax error near unexpected token `newline'
-bash: command substitution: line 1: `docker pull jahia/<< parameters.docker_repo >>:<< parameters.docker_image_tag >>'
~$ export DOCKER_COMMAND="\`\`\`docker pull jahia/<< parameters.docker_repo >>:<< parameters.docker_image_tag >>\`\`\`"
~$ echo $DOCKER_COMMAND
```docker pull jahia/<< parameters.docker_repo >>:<< …
> Escape special characters

- src/jobs/initialize.yml
- src/jobs/integration-tests.yml
- src/jobs/static-analysis.yml
I was initially using "large" as the default resource class for integration tests, but I suspect this was actually the cause of some flakiness. Increased to xlarge (the prior config for integration tests with Jahia).
> [semver:patch] - Fixed some yarn issues and changed default resource class for integration tests

- .gitignore
- src/commands/sonar-analysis.yml
- src/examples/sonar-analysis.yml
- src/jobs/sonar-analysis.yml
https://jira.jahia.org/browse/SELENIUM-1462
For branches the sonar.projectKey was taken from Maven, but for the primary release branch and for PRs it was explicitly set, leading to duplicated projects on SonarQube.
I think it is better to take the one from Maven as it has the groupId and the artifactId - less risk of conflict.
This inconsistency is there since the beginning of the sandbox module, so it has spread to other modules. We will have to adapt there, too, and then we need to delete the duplicated projects on SonarQube (the ones having the primary release branch).
Actually the passing of the module_id parameter is even no longer necessary as the parameter is not used inside. We should maybe delete it, which should be done carefully as it is an orb function now - unless we want to …
> SELENIUM-1462: fix inconsistency in setting the sonar.projectKey

- src/commands/sonar-analysis.yml
Use org.owasp:dependency-check-maven instead of just dependency-check to make Maven find the plugin without the need to configure the <pluginGroups> in settings.xml or the plugin in pom.xml
> Help Maven find the dependency-check plugin from command line

- src/commands/sonar-analysis.yml
Use hardcoded 6.1.6 version of dependency-check-maven as this problem is running into timeouts : https://github.com/jeremylong/DependencyCheck/issues/3408 
We should then rather set a configured version in jahia-parent/pom.xml
> step back to 6.1.6 version of the dependency-check plugin

- src/commands/security.yml
- src/commands/sonar-analysis.yml
- src/jobs/integration-tests.yml
- src/jobs/sonar-analysis.yml
- src/jobs/static-analysis.yml
- Added variable to differentiate audit-ci between module and tests codebases. Changed the default for tests to critical
- Added a no_output_timetout to sonar-analysis job and command
- Added debug data (images in cache) to the integration tests job
> [semver:patch] - Various updates to the orb (audit-ci, sonar, integration tests)

- src/jobs/build.yml
This allows the first build of a project with sub project with inner dependencies.
Currently the command:
```
mvn -s .circleci/.circleci.settings.xml dependency:copy-dependencies
```
fail when switching to a new version because the local repository does not contain the new version artifacts.
See: https://app.circleci.com/pipelines/github/Jahia/jexperience/595/workflows/98beb69d-2fcb-4a10-a6de-395f263b249f/jobs/1533
This change fill the repository with all required artefacts.
> fix first build  of sub projects

- src/commands/sonar-analysis.yml
With https://jira.jahia.org/browse/BACKLOG-14111 we added a git related workaround before the pull-request Sonar check, because of CircleCI bug, which got fixed with: 
https://discuss.circleci.com/t/git-checkout-of-a-branch-destroys-local-reference-to-master/23781/16
On jahia-private we did that removal already 3 months ago and its good.
> Remove git workaround

- src/jobs/initialize.yml
The cache was not using the same key between save and restore, resulting in it being re-generated every time.
> [semver:patch] - Fixed issue with npm cache

- src/commands/security.yml
https://jira.jahia.org/browse/TECH-210
Right now Audit CI is flagging moderate vulnerabilities and stopping build. I think had a discussion with @bpapez before that we should be ok setting this at least to "high" level instead.
> Fail Audit-CI on high level and above only

- src/commands/code-signer.yml
Change from batch signing to iterate individual installer files since we need to be able to overwrite in the same directory and we can't move them around.
> BACKLOG-16374: iterate code signing instead of batch

- src/jobs/integration-tests-machine.yml
As per the docs:
https://circleci.com/docs/2.0/configuration-reference/#machine
> Update Ubuntu image used for machine executor

- src/jobs/integration-tests-remote-circleci.yml
This is to support use cases such as `kibana-dashboards`.
> [semver:minor] - Added a job to trigger execution of the integration tests in a remote repo

- src/commands/integration-tests.yml
Dealing with incident assignees in Pagerduty is not the easiest.
If I understand the logic properly, PargerDuty does not have a notion of slack notifications in the desired method a user can choose from (only email, phone, pagerduty app). If a user is not "on-call" when an incident is created, he/she does not get pinged on slack (`@user`), his/her name is shown on slack as attached to the ticket but this does not generate notifications.
In our use case we don't want anyone to be "on-call" for such incidents, but only be notified on slack (no email, no phone, no pagerduty app) when a new incident is created.
When an incident is re-assigned to a user, this user gets notified on slack, no matter to the on-call schedule.
This allows us to ensure that a user is actually notified on slack when …
> [semver:patch] - Updated the command to use the latest version of jahia-reporter

- src/commands/integration-tests.yml
The reason for switching to xml for jahia-reporter is to allow the Selenium tests (which don't support json reports) to have their report also processed by the integration tests orb command.
We still keep the json (and the counterpart single-file report) as a user-friendly way to look at the reports in the artifacts folder.
> [semver:patch] - Updated the integration tests to use XML reports instead of json

- src/commands/sonar-analysis.yml
https://jira.jahia.org/browse/INFRA-2009
Set skipSystemScope to true to avoid the Analysis exception "Unable to resolve system scoped dependency: com.sun:tools:jar:1.8.0:system" being displayed in the OWASP dependency check dashboard.
The following are included in this PR
I have considered the following implications of my change:
> [semver:patch] - INFRA-2009: set skipSystemScope to true in OWASP check

- src/jobs/build.yml
- src/jobs/release.yml
- src/jobs/sonar-analysis.yml
This was needed to fix an issue with the release job.
I'll wait for the cimg image to be available before merging: https://app.circleci.com/pipelines/github/Jahia/cimg-mvn-cache/218/workflows/d05dd563-83a4-4013-9844-0ff46432fd59/jobs/229
> [semver:patch] - Updated to the lates jahia/cimg-mvn-cache docker image

- src/commands/integration-tests.yml
This is necessary to migrate the workflow on jahia-ee to use the orb.
> [semver:minor] - Load the image.tar file if present

- src/commands/integration-tests.yml
- src/jobs/integration-tests-machine.yml
- src/jobs/integration-tests.yml
This will cover cases for which we want to report execution differently based on a defined service.
For example, one reporting path for cluster, one reporting path for non cluster.
> Add the ability to specify a service different from module ID.

- src/commands/update-module-signature.yml
https://jira.jahia.org/browse/TECH-592
Call to `update-module-signature` fails unexpectedly when there are no modules to sign. This is because Circle CI adds `-eo pipefail` option and that a `grep` call with no matches returns a failure exit code.
Mask grep exit code by adding `|| true` and treat `modules_to_sign` as empty
> TECH-592: Prevent command from failing when no match
