src/commands/generate-cachekey-seed.yml
src/jobs/sonar-analysis.yml

[semver:patch] - Fixed typos

---

src/commands/lint.yml
src/commands/security.yml
src/jobs/build.yml
src/jobs/docker-publish-tests.yml
src/jobs/initialize.yml
src/jobs/publish.yml
src/jobs/static-analysis.yml

[semver:patch] - Added more commands and jobs

---

src/commands/integration-tests.yml

Simplified the command following discussion with Thomas and Cedric

Updated the integration tests

---

src/commands/integration-tests.yml
src/jobs/integration-tests.yml

Added integration tests job

---

src/commands/update-signature-prestep.yml
src/jobs/generate-changelog.yml
src/jobs/integration-tests.yml
src/jobs/release-cancellation.yml
src/jobs/release-publication.yml
src/jobs/release-rollback.yml
src/jobs/release.yml
src/jobs/update-signature.yml

Description is in the title, this wraps-up porting config elements from the sandbox repo to this orb.

[semver:minor] - Ported the remaining config elements to the orb

---

src/commands/lint.yml
src/commands/security.yml
src/jobs/initialize.yml

[semver:patch] - Fixed incorrect filename in intialize, linting and security

---

src/commands/lint.yml
src/commands/security.yml
src/jobs/initialize.yml

[semver:patch] - Fixed issue with yarn cache

---

README.md
src/commands/lint.yml
src/commands/security.yml
src/jobs/initialize.yml
src/jobs/static-analysis.yml

Description in the title.
This is to fix this failure: https://app.circleci.com/pipelines/github/Jahia/sandbox/1336/workflows/8d07b37c-f71a-4ba3-86ef-cfba2ea37467/jobs/3986

Prevent an issue if eslint is not available

---

src/jobs/build.yml

[semver:patch] - Minor fixes in the build job while updating graphql-core repo setup

---

src/jobs/build.yml

[semver:patch] - Minor fixes in the build job

---

src/jobs/integration-tests.yml

This helps clear out if the correct container is running (or not)

Added some messages to verify the hashes of running containers

---

src/jobs/build.yml

https://jira.jahia.org/browse/DMF-4671

DMF-4671 : update build to consider sub modules

---

src/jobs/release.yml

https://jira.jahia.org/browse/DMF-4671

DMF-4671 : copy jar from sub directories to the artifact directory

---

src/commands/integration-tests.yml

This update follows this PR: https://github.com/Jahia/jahia-reporter/pull/31

Update parameters for the slack call

---

src/jobs/initialize.yml

The description is in the title, this is similar to what was done for the build job.

Added support for base image via parameter

---

src/jobs/initialize.yml

Added the ability to specify which base image to use with the initialize job

[semver:patch] - Added support for base image via parameter (#50)

---

src/jobs/build.yml

[semver:patch] - Copy only jahia modules as dependency

---

src/commands/code-signer.yml

Add code signer orb - loop through jar/exe files using `file_pattern` in a given `installer_dir`

BACKLOG-16374: Add code signer orb

---

src/commands/code-signer.yml

Fix issues:
- Fix install of oathtool
- Combine step of retrieving access token and the signer curl calls since env vars are not shareable between run steps

BACKLOG-16374: Fix code-signer issues

---

src/README.md

semver:patch tag release for PR https://github.com/Jahia/jahia-modules-orb/pull/55

[semver:patch] - Force orb release

---

src/commands/code-signer.yml

Switch to using CodeSignTool for batch signing installers https://www.ssl.com/guide/esigner-codesigntool-command-guide/#ftoc-heading-7

BACKLOG-16374: Use CodeSignTool for code signing

---

src/commands/code-signer.yml

BACKLOG-16374: Fix typo

---

README.md

BACKLOG-16374: Force orb release

---

src/commands/integration-tests.yml

Updated the integration tests command to use @jahia/jahia-reporter

---

src/jobs/integration-tests.yml

issue: "error An unexpected error occurred: "EPERM: operation not permitted, copyfile"
See https://github.com/yarnpkg/yarn/issues/8389

[semver:patch] - Fix build of tests image

---

src/commands/update-module-signature.yml
src/jobs/update-signature.yml

https://jira.jahia.org/browse/BACKLOG-16566

BACKLOG-16566 : add update command

---

src/jobs/build.yml

[semver:patch] - In build job, fixed persist workspace for modules building in folders 

---

src/jobs/release.yml

Updated orb to use the maven cached docker image for release

---

src/commands/code-signer.yml

https://jira.jahia.org/browse/BACKLOG-16662

BACKLOG-16662 - Extract CodeSignTool content in a generic folder

---

src/commands/code-signer.yml

https://jira.jahia.org/browse/BACKLOG-16662

BACKLOG-16662- Update permissions

---

src/commands/code-signer.yml

https://jira.jahia.org/browse/BACKLOG-16706
Used to differenciate sandbox and prod tools

BACKLOG-16706 - Add parameter to provide url to download CodeSignTool

---

src/commands/integration-tests.yml

- Added the compose file as an environment variable
These changes are needed for: https://github.com/Jahia/jahia-ee/pull/253

[semver:patch] - Preparations to make the orb compatible with jahia-ee

---

src/commands/update-module-signature.yml

https://jira.jahia.org/browse/BACKLOG-16689

BACKLOG-16689 : check if there is modules to sign before execution

---

src/jobs/build.yml
src/jobs/release.yml
src/jobs/sonar-analysis.yml

The description is in the title.
Slack discussion: https://jahia.slack.com/archives/C018KF0N142/p1643078455009600

[semver:minor] - Adding docker hub credentials to fetch from private repository

---

README.md

QA-14152: Trigger patch version creation/upload

[semver:patch] Trigger creation/upload

---

src/commands/update-module-signature.yml

https://jira.jahia.org/browse/TECH-808

TECH-808: Add dry run parameter for module signing command

---

src/commands/update-module-signature.yml

https://jira.jahia.org/browse/TECH-808

TECH-808: Fix keymaker-cli jar url

---

src/commands/update-module-signature.yml

https://jira.jahia.org/browse/BACKLOG-17260
* Bad logic when checking for dry_run
* Skip modules with errors instead of failing (so we don't block rest of modules to process)
* Additional logging

BACKLOG-17260: Module signature fixes; additional logging
